version: '3.8'

services:

  sql-db:
    image: postgres:15.2
    container_name: gestion_pedidos_R
    restart: always
    volumes:
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/data.sql
    environment:
      - POSTGRES_DB=gestion_pedidos
      - POSTGRES_USER=joel
      - POSTGRES_PASSWORD=200302
    ports:
      - "5432:5432"
  mongo-db:
    image: mongo:6.0.4
    restart: always
    container_name: gestion_pedidos_NR
    environment:
      MONGO_INITDB_ROOT_USERNAME: joel
      MONGO_INITDB_ROOT_PASSWORD: jalixto
      MONGO_INITDB_DATABASE: gestion_pedidos
    ports:
        - "27017:27017"
    volumes:
      - ./db/mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
